"""Add color column to Team model

Revision ID: 5560e6ccb169
Revises: eef960a668eb
Create Date: 2024-08-14 11:18:51.511592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5560e6ccb169'
down_revision: Union[str, None] = 'eef960a668eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'color')
    # ### end Alembic commands ###
