"""empty message

Revision ID: 9c98b10c6005
Revises: 
Create Date: 2024-08-09 08:05:55.570805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c98b10c6005'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_rooms',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_meeting_rooms_key'), 'meeting_rooms', ['key'], unique=False)
    op.create_index(op.f('ix_meeting_rooms_name'), 'meeting_rooms', ['name'], unique=False)
    op.create_table('teams',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_teams_key'), 'teams', ['key'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('reservations',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('roomKey', sa.Integer(), nullable=True),
    sa.Column('teamKey', sa.Integer(), nullable=True),
    sa.Column('bookDate', sa.Date(), nullable=True),
    sa.Column('startTime', sa.Time(), nullable=True),
    sa.Column('endTime', sa.Time(), nullable=True),
    sa.Column('teamName', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['roomKey'], ['meeting_rooms.key'], ),
    sa.ForeignKeyConstraint(['teamKey'], ['teams.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_reservations_key'), 'reservations', ['key'], unique=False)
    op.create_table('users',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['teams.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_users_key'), 'users', ['key'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reservations_key'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_key'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_meeting_rooms_name'), table_name='meeting_rooms')
    op.drop_index(op.f('ix_meeting_rooms_key'), table_name='meeting_rooms')
    op.drop_table('meeting_rooms')
    # ### end Alembic commands ###
